# Generated by Django 5.0.3 on 2024-03-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksAuthor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('birth_year', models.SmallIntegerField(blank=True, null=True)),
                ('death_year', models.SmallIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'books_author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BooksBook',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('download_count', models.IntegerField(blank=True, null=True)),
                ('gutenberg_id', models.IntegerField()),
                ('media_type', models.CharField(max_length=16)),
                ('title', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'books_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BooksBookAuthors',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_id', models.IntegerField()),
                ('author_id', models.IntegerField()),
            ],
            options={
                'db_table': 'books_book_authors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BooksBookBookshelves',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_id', models.IntegerField()),
                ('bookshelf_id', models.IntegerField()),
            ],
            options={
                'db_table': 'books_book_bookshelves',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BooksBookLanguages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_id', models.IntegerField()),
                ('language_id', models.IntegerField()),
            ],
            options={
                'db_table': 'books_book_languages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BooksBookshelf',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'books_bookshelf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BooksBookSubjects',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_id', models.IntegerField()),
                ('subject_id', models.IntegerField()),
            ],
            options={
                'db_table': 'books_book_subjects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BooksFormat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mime_type', models.CharField(max_length=32)),
                ('url', models.TextField()),
                ('book_id', models.IntegerField()),
            ],
            options={
                'db_table': 'books_format',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BooksLanguage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'books_language',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BooksSubject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'books_subject',
                'managed': False,
            },
        ),
    ]
