# Generated by Django 5.0.3 on 2024-03-16 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORMapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booksauthor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='booksbook',
            options={},
        ),
        migrations.AlterModelOptions(
            name='booksbookauthors',
            options={},
        ),
        migrations.AlterModelOptions(
            name='booksbookbookshelves',
            options={},
        ),
        migrations.AlterModelOptions(
            name='booksbooklanguages',
            options={},
        ),
        migrations.AlterModelOptions(
            name='booksbookshelf',
            options={},
        ),
        migrations.AlterModelOptions(
            name='booksbooksubjects',
            options={},
        ),
        migrations.AlterModelOptions(
            name='booksformat',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bookslanguage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bookssubject',
            options={},
        ),
    ]
