# Generated by Django 5.0.3 on 2024-03-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORMapp', '0003_alter_booksauthor_options_alter_booksbook_options_and_more'),
    ]

    operations = [
    ]
