# Generated by Django 5.0.3 on 2024-03-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORMapp', '0004_auto_20240316_1142'),
    ]

    operations = [
    ]
