# Generated by Django 5.0.3 on 2024-03-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORMapp', '0007_auto_20240316_1234'),
    ]

    operations = [
    ]
