# Generated by Django 5.0.3 on 2024-03-16 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORMapp', '0008_auto_20240316_1245'),
    ]

    operations = [
    ]
