# Generated by Django 5.0.3 on 2024-03-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORMapp', '0011_auto_20240316_1301'),
    ]

    operations = [
    ]
