# Generated by Django 5.0.3 on 2024-03-16 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORMapp', '0015_auto_20240316_1322'),
    ]

    operations = [
    ]
