# Generated by Django 5.0.3 on 2024-03-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORMapp', '0016_auto_20240316_1655'),
    ]

    operations = [
    ]
