# Generated by Django 5.0.3 on 2024-03-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORMapp', '0017_auto_20240316_1744'),
    ]

    operations = [
    ]
