# Generated by Django 5.0.3 on 2024-03-16 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORMapp', '0020_auto_20240316_1833'),
    ]

    operations = [
    ]
