# Generated by Django 5.0.3 on 2024-03-16 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORMapp', '0021_auto_20240316_1836'),
    ]

    operations = [
    ]
