# Generated by Django 5.0.3 on 2024-03-16 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORMapp', '0023_auto_20240316_1847'),
    ]

    operations = [
    ]
