# Generated by Django 5.0.3 on 2024-03-17 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORMapp', '0024_auto_20240316_1849'),
    ]

    operations = [
    ]
