# Generated by Django 5.0.3 on 2024-03-17 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORMapp', '0026_auto_20240317_0438'),
    ]

    operations = [
    ]
