# Generated by Django 5.0.3 on 2024-03-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORMapp', '0027_auto_20240317_0453'),
    ]

    operations = [
    ]
