# Generated by Django 5.0.3 on 2024-03-17 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORMapp', '0028_auto_20240317_1335'),
    ]

    operations = [
    ]
